spring:
  jpa:
    show-sql: false
  liquibase:
    contexts: prod

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET}
  card-encryption:
    secret: ${CARD_ENCRYPTION_SECRET}

logging:
  level:
    root: INFO
    com.example.bankcards: INFO
